todoapp/todoapp/urls.py
from django.urls import path, include
from todos.views import index


urlpatterns = [
    path('', index, name='index'),
    path('todos/', include('todos.urls', namespace="todos")),
]

todoapp/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('update/<int:pk>/', views.update_todo, name='update_todo'),
    path('delete/<int:pk>/', views.delete_todo, name='delete_todo'),
    path('toggle/todo/<int:todo_id>/', views.toggle_todo, name='toggle_todo'),
    path('change_todo_order/<int:todo_id>/<str:direction>/', views.change_todo_order, name='change_todo_order'),
    path('filter_by_priority/', views.filter_by_priority, name='filter_by_priority'),
]

todoapp/todos/models.py
from django.core.exceptions import ValidationError
from django.db import models

class Todo(models.Model):
    PRIORITY_CHOICES = [
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
    ]
    task = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=6, choices=PRIORITY_CHOICES, default='Low')
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.task

    class Meta:
        ordering = ['order']

todoapp/todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    order = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Todo
        fields = ['task', 'priority', 'order']

todoapp/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.shortcuts import get_object_or_404
from .forms import TodoForm
from django.db.models import Max
from django.contrib import messages
import time

app_name = 'todos'

# Dictionary to store the last time a change_todo_order request was made for each todo
last_change_request = {}

def index(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todos = Todo.objects.all()
            max_order = todos.aggregate(Max('order'))['order__max'] or 0
            new_todo = form.save(commit=False)
            new_todo.order = max_order + 1
            new_todo.save()
            return redirect('todos:index')
    else:
        form = TodoForm()
    todos = Todo.objects.all()
    context = {'form': form, 'todos': todos, 'PRIORITY_CHOICES': Todo.PRIORITY_CHOICES}
    return render(request, 'todos/index.html', context)

def delete_todo(request, pk):
    todo = get_object_or_404(Todo, id=pk)
    todo.delete()
    return redirect('todos:index')

def update_todo(request, pk):
    todo = Todo.objects.get(id=pk)

    if request.method == 'POST':
        todo.task = request.POST['task']
        todo.completed = request.POST.get('completed', False) == "on"
        todo.priority = request.POST['priority']
        todo.save()
        return redirect('todos:index')

    context = {
        'todo': todo,
        'PRIORITY_CHOICES': Todo.PRIORITY_CHOICES,
    }
    return render(request, 'todos/update_todo.html', context)

def toggle_todo(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.completed = not todo.completed
    todo.save()
    todos = Todo.objects.all()
    return redirect('todos:index')

def change_todo_order(request, todo_id, direction):
    todo = get_object_or_404(Todo, pk=todo_id)
    current_time = time.time()
    last_request_time = last_change_request.get(todo_id, 0)
    if current_time - last_request_time < 1:
        messages.error(request, 'Too many requests, try again later.')
        return redirect('todos:index')
    last_change_request[todo_id] = current_time
    todos = Todo.objects.all().order_by("order")
    todos_list = list(todos)
    current_index = todos_list.index(todo)
    if direction == 'up':
        if current_index > 0:
            todo_swap = todos_list[current_index - 1]
            todo.order, todo_swap.order = todo_swap.order, todo.order
            todo.save()
            todo_swap.save()
    else:
        if current_index < len(todos_list) - 1:
            todo_swap = todos_list[current_index + 1]
            todo.order, todo_swap.order = todo_swap.order, todo.order
            todo.save()
            todo_swap.save()
    return redirect('todos:index')

def filter_by_priority(request):
    selected_priority = request.GET.get('priority')
    if selected_priority:
        todos = Todo.objects.filter(priority=selected_priority)
    else:
        todos = Todo.objects.all()
    context = {'todos': todos, 'selected_priority': selected_priority, 'PRIORITY_CHOICES': Todo.PRIORITY_CHOICES}
    return render(request, 'todos/index.html', context)

todoapp/todos/templates/todos/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <title>Todo App</title>
  <nav class="flex items-center justify-between flex-wrap bg-gray-800 p-3">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <span class="font-semibold text-xl tracking-tight pr-44">Taskify</span>
    </div>
    <div class="block lg:hidden">
      <button
        class="fixed w-full flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
        </svg>
      </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:w-auto">
      <div class="text-sm mr-4">
        <div class="flex items-center w-full">
          <form action="{% url 'todos:index' %}" method="post">
            {% csrf_token %}
            {{ form.task }}
            {{ form.priority }}
            <input type="submit" value="Add Task" class="bg-blue-500 text-white p-2 rounded border-1 text-sm border-white  hover:text-white-700 hover:bg-blue-700 mt-4 lg:mt-0 ml-4">
          </form>
          <form method="get" action="{% url 'todos:filter_by_priority' %}" class="ml-4">
            <select name="priority" id="priority">
              <option value="">All</option>
              {% for priority, display in PRIORITY_CHOICES %}
                <option value="{{ priority }}"{% if priority == selected_priority %} selected{% endif %}>{{ display }}</option>
              {% endfor %}
            </select>
            <button type="submit" class="bg-yellow-500 text-white p-2 rounded border-1 text-sm border-white  hover:text-white-700 hover:bg-yellow-700 mt-4 lg:mt-0 ml-4">Filter</button>
          </form>
        </div>
      </div>
    
    <style>
      form input[type="text"], form select {
        height: 30px;
        font-size: 15px;
        padding: 2px 10px;
        border: 1px solid #ccc;
      }
      .priority-High {
        background-color: rgba(255, 0, 0, 0.3);
      }
      
      .priority-Medium {
        background-color: rgba(255, 255, 0, 0.3);
      }
      
      .priority-Low {
        background-color: rgba(0, 255, 0, 0.3);
      }
      .completed-background {
        background-color: rgba(0, 255, 0, 0.3);
      }
    </style>

    </div>
    </div>
  </nav>
</head>


<body class="">
  
  <div class="mt-10 mr-1">
    <table class="table-auto w-fit mt-4 border border-gray-400 mx-auto">
      <thead class="bg-gray-200">
        <tr>
          <th class="px-4 py-2 border border-gray-300 ">Order</th>
          <th class="px-4 py-2 border border-gray-300">Task</th>
          <th class="px-4 py-2 border border-gray-300">Priority</th>
          <th class="px-4 py-2 border border-gray-300">Completed</th>
          <th class="px-4 py-2 border border-gray-300">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for todo in todos %}
        <tr class="{% cycle 'bg-white' 'bg-gray-100' %} {%if todo.completed %}bg-green-100{% endif %}">
          <td class="border px-4"><div class="flex flex-col w-min">
            <a href="{% url 'todos:change_todo_order' todo.id 'up' %}" class=" text-black font-bold py-2 px-3 rounded">
              ↑
            </a>
            <a href="{% url 'todos:change_todo_order' todo.id 'down' %}" class="text-black font-bold py-2 px-3 rounded">
              ↓
            </a>
          </div></td>
          <td class="border px-4 py-2 w-5/12 {%if todo.completed %}text-decoration: line-through{% endif %}">{{ todo.task }}</td>
          <td class="border px-4 py-2 w-2/12 text-center priority-{{ todo.priority }} {% if todo.completed %}completed{% endif %}">{{ todo.priority }}</td>
          <td class="border px-4 text-center">
            <input type="checkbox" class="w-4 h-4 text-green-600 bg-gray-100 border-gray-300 rounded focus:ring-green-500 dark:focus:ring-green-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" {% if todo.completed %}checked{% endif %}
              onclick="window.location='{% url 'todos:toggle_todo' todo.id %}'">
          </td>
          <td class="border px-4 pt-3 pb-3 py-2  text-center">
            <a href="{% url 'todos:update_todo' todo.id %}"
            class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
             Edit
            </a>
            <span class="px-1"></span>
            <a href="{% url 'todos:delete_todo' todo.id %}"
            class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
             Delete
            </a>
            
          </td>
          
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</body>
</html>

todoapp/todos/templates/todos/update_todo.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <title>Todo App</title>
</head>

<body class="p-4">
  <nav class="flex items-center justify-between flex-wrap bg-gray-800 p-4">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
      <span class="font-semibold text-xl tracking-tight">Taskify</span>
    </div>
  </nav>
  <div class="container mx-auto mt-10">
    <h1 class="text-2xl text-center font-bold">Update To-do</h1>
    <form method="post" class="mt-10 mx-auto w-5/12 p-10 bg-white rounded">
      {% csrf_token %}
      <div class="mb-4 w-6/12 mx-auto">
        <label class="block text-gray-700 font-medium mb-2">Update Task</label>
        <input type="text" name="task" value="{{ todo.task }}" class="border border-gray-400 p-2 w-full">
        <label class="block text-gray-700 font-medium mb-2">Priority</label>
        <select name="priority" class="border border-gray-400 p-2 pr-0 w-4/12">
          <option value="Low" {% if todo.priority == 'Low' %} selected {% endif %}>Low</option>
          <option value="Medium" {% if todo.priority == 'Medium' %} selected {% endif %}>Medium</option>
          <option value="High" {% if todo.priority == 'High' %} selected {% endif %}>High</option>
        </select </div> <div class="mb-4 w-2/12 mx-auto">


      </div>
      <div class="mb-4 text-center">
        <input type="submit" value="Update"
          class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">
        <a href="{% url 'todos:index' %}"
          class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Back</a>
      </div>
    </form>
  </div>
</body>

</html>